### ISSUE TITLE
Revise docs for UsbBus::reset(), to indicate it should handle a bus reset

### ISSUE THREAD

**Issue by twitchyliquid64** [mvirkkunen/usb-device#25]
The doc string on `UsbBus::reset()` says:

```rust
/// Performs a USB reset. This method should reset the platform-specific peripheral as well as
/// ensure that all endpoints previously allocate with alloc_ep are initialized as specified.
fn reset(&self);
```

However, `reset()` is called whenever `poll()` returns `PollResult::Reset`, which symbolizes a USB protocol reset by the host. This does not necessarily mean the USB peripheral should be completely reset. In my case, performing a peripheral reset results in a detached state for more than a frame, which is breaking things.

Instead of suggesting the peripheral specific driver should reset the peripheral, can we re-word this to indicate that the reset method should handle a protocol reset? I am currently working on a driver for the ATSAMD51, and this bit me :)

Random idea for wording:

```rust
/// Handles a USB protocol reset signaled from the host. This method should reset the state
/// of all endpoints and peripheral flags back to a state compatible with host enumeration,
/// as well as ensure that all endpoints previously allocated with alloc_ep are initialized
/// as specified.
fn reset(&self);
```

**Comment by mvirkkunen** [comment]
Good point. The wording isn't very good at the moment.
